/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */

import handler from 'vinext/server/app-router-entry';
import {
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  handleImageOptimization,
} from 'vinext/server/image-optimization';

interface Env {
  ASSETS: Fetcher;
  SEARCH_CACHE: KVNamespace;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
  RAKUTEN_APP_ID: string;
  RAKUTEN_ACCESS_KEY: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

async function syncHotelInfo(env: Env): Promise<string> {
  const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseKey) {
    throw new Error(
      'SUPABASE_SERVICE_ROLE_KEY is required for sync operations',
    );
  }
  const appId = env.RAKUTEN_APP_ID;
  const accessKey = env.RAKUTEN_ACCESS_KEY;
  const apiBase =
    'https://openapi.rakuten.co.jp/engine/api/Travel/SimpleHotelSearch/20170426';
  const origin = 'https://furo-tabi.mui-co.workers.dev';

  const dbRes = await fetch(
    `${supabaseUrl}/rest/v1/hotels?select=id,rakuten_hotel_id,name&limit=1000`,
    {
      headers: { apikey: supabaseKey, Authorization: `Bearer ${supabaseKey}` },
    },
  );
  const hotels = (await dbRes.json()) as Array<{
    id: string;
    rakuten_hotel_id: number;
    name: string;
  }>;

  let updated = 0;
  let notFound = 0;

  for (const h of hotels) {
    const res = await fetch(
      `${apiBase}?applicationId=${appId}&accessKey=${accessKey}&format=json&hotelNo=${h.rakuten_hotel_id}`,
      { headers: { Origin: origin } },
    );
    if (!res.ok) {
      notFound++;
      continue;
    }

    const data = (await res.json()) as Record<string, unknown>;
    const hotelsArr = data.hotels as
      | Array<{ hotel: Array<{ hotelBasicInfo?: Record<string, unknown> }> }>
      | undefined;
    const info = hotelsArr?.[0]?.hotel?.[0]?.hotelBasicInfo;
    if (!info) {
      notFound++;
      continue;
    }

    // 画像・料金・都道府県のみ更新（nameはCSV優先）
    const patch: Record<string, unknown> = {
      image_url: (info.hotelImageUrl as string) || '',
      min_charge: (info.hotelMinCharge as number) || 0,
      prefecture: (info.address1 as string) || '',
    };
    if (!h.name) {
      patch.name = (info.hotelName as string) || '';
    }

    await fetch(`${supabaseUrl}/rest/v1/hotels?id=eq.${h.id}`, {
      method: 'PATCH',
      headers: {
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`,
        'Content-Type': 'application/json',
        Prefer: 'return=minimal',
      },
      body: JSON.stringify(patch),
    });
    updated++;
  }

  return `Synced ${hotels.length} hotels: ${updated} updated, ${notFound} not found`;
}

export default {
  async scheduled(
    _event: ScheduledEvent,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<void> {
    globalThis.__FURO_TABI_SEARCH_CACHE = env.SEARCH_CACHE;
    ctx.waitUntil(
      syncHotelInfo(env).then((msg) => console.log(`[CRON] ${msg}`)),
    );
  },

  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    globalThis.__FURO_TABI_SEARCH_CACHE = env.SEARCH_CACHE;
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === '/_vinext/image') {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => {
            if (path.startsWith('http://') || path.startsWith('https://')) {
              return fetch(path);
            }
            return env.ASSETS.fetch(new Request(new URL(path, request.url)));
          },
          transformImage: async (body, { width, format, quality }) => {
            try {
              const result = await env.IMAGES.input(body)
                .transform(width > 0 ? { width } : {})
                .output({ format, quality });
              return result.response();
            } catch {
              // Cloudflare Images not enabled — return original image
              return new Response(body, {
                headers: {
                  'Content-Type': `image/${format}`,
                  'Cache-Control': 'public, max-age=86400',
                },
              });
            }
          },
        },
        allowedWidths,
      );
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
